version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "applause-button"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-59tvfqp4psgm"
s3_prefix = "applause-button"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

