AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  applause-button

  Sample SAM Template for applause-button

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
  Api:
    Cors: "'*'"

Resources:
  ApplauseButtonFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: applause-button/
      Handler: applause-button
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GetApplauses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /applause-button
            Method: GET
        UpdateApplauses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /applause-button
            Method: PUT
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
  ApplauseButtonDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: applause-button-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApplauseButtonAPI:
    Description: "API Gateway endpoint URL for Prod environment for Applause Button"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/applause-button/"
  ApplauseButtonFunction:
    Description: "Applause Button Function ARN"
    Value: !GetAtt ApplauseButtonFunction.Arn
  ApplauseButtonFunctionIamRole:
    Description: "Implicit IAM Role created for Applause Button function"
    Value: !GetAtt ApplauseButtonFunctionRole.Arn
  ApplauseButtonDynamoDBTable:
    Description: "Applause Button Dynamo DB Table ARN"
    Value: !GetAtt ApplauseButtonDynamoDBTable.Arn
